// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_cnn_general (
hls::stream<ap_fixed<24, 7, (ap_q_mode) 5, (ap_o_mode)0, 0> > (&in),
hls::stream<ap_fixed<24, 7, (ap_q_mode) 5, (ap_o_mode)0, 0> > (&out),
int size,
int in_layers,
int out_layers,
bool stream_weights,
int max_type);
